version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/fizzbuzz

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm install jest-junit
      - run: sudo npm install -g jest
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run Test
          command: mkdir test-results && jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/test-results.xml
      - store_artifacts:
          path: test-results
          prefix: test
      - store_test_results:
          path: test-results
